### ISSUE TITLE
Cant read fasta file with long line.

### ISSUE THREAD

**Issue by LafontRapnouilTristan** [Bioconductor/ShortRead#15]
Hello,

while trying to import sequences from a .fasta file I encounter the following error :
```cannot read line 14348, line is too long```  (and indeed it is long:  25157 character)

In encounter the same error while trying to use ```Biostrings``` packages.
Do you have any suggestions on how I could resolve this issue?

The error occurs in the getSequences function from dada2 that is using ShortRead to read .fasta for taxonomic assignment.

Here is my sessioninfo:
![image](https://github.com/Bioconductor/ShortRead/assets/49724216/fa75a66f-a694-483c-9eaa-8122f7b8528e)

Let me know if you need anything more to address this issue.

Thanks for your work and have a nice day!

**Comment by hpages** [comment]
The problem actually originates in **Biostrings**. See https://github.com/Bioconductor/Biostrings/issues/59
