### ISSUE TITLE
ShortRead fails test test_readPrb.R for non-Intel architectures

### ISSUE THREAD

**Issue by mr-c** [Bioconductor/ShortRead#4]
[the below was sent to Bioconductor Package Maintainer <maintainer@bioconductor.org> by @tillea but I didn't see any response, so I thought I'd try here]

Hi,

the Debian packaged ShortRead is tested in CI test on different hardware
architectures.  On the debci page[1] you can see the matrix for success
and failure which shows that amd64 and i386 are passing the complete
test suite while other architectures are failing.  In those failing cases
the test log says something like

```
Timing stopped at: 1.012 0.02 1.031
Error in checkIdentical(exp, as(readPrb(sp, ".*prb.txt", as = "FastqEncoding"),  : 
  FALSE 
 
In addition: Warning messages:
1: In .class1(object) :
  closing unused connection 6 (/usr/lib/R/site-library/ShortRead/extdata/Data/C1-36Firecrest/Bustard/GERALD/s_1_sequence.txt)
2: In .class1(object) :
  closing unused connection 5 (/usr/lib/R/site-library/ShortRead/extdata/Data/C1-36Firecrest/Bustard/GERALD/s_1_sequence.txt)
Timing stopped at: 0.028 0.001 0.031
Error in checkIdentical(36L, unique(width(obj))) : FALSE 
 


RUNIT TEST PROTOCOL -- Sun Jan 24 21:54:15 2021 
*********************************************** 
Number of test functions: 104 
Number of errors: 0 
Number of failures: 2 

 
1 Test Suite : 
ShortRead RUnit Tests - 104 test functions, 0 errors, 2 failures
FAILURE in test_readPrb_consistent: Error in checkIdentical(exp, as(readPrb(sp, ".*prb.txt", as = "FastqEncoding"),  : 
  FALSE 
 
FAILURE in test_readPrb_input: Error in checkIdentical(36L, unique(width(obj))) : FALSE 
 

Test files with failing tests

   test_readPrb.R 
     test_readPrb_consistent 
     test_readPrb_input 


Error in BiocGenerics:::testPackage("ShortRead") : 
  unit tests failed for package ShortRead
In addition: Warning message:
In is.factor(x) :
  closing unused connection 3 (/tmp/RtmpEinleR/file1d7b55bbcf1b)
Execution halted
```

When removing the file test_readPrb.R from the installation the tests
are passing but before I do such nasty things I'd like to clarify the
situation with you.

Kind regards

      Andreas.

[1] https://ci.debian.net/packages/r/r-bioc-shortread/

**Comment by mtmorgan** [comment]
Is there some way to easily reproduce one of these failing environments, e.g., a docker image?

**Comment by mr-c** [comment]
Ah, the issue seems to be on our side. The test pass in Debian "Unstable", but not Debian "testing", so probably we need to wait for some more dependencies to migrate to  "testing". Sorry to bother!
