### ISSUE TITLE
WISH: Add URL and BugReports to DESCRIPTION

### ISSUE THREAD

**Issue by HenrikBengtsson** [Bioconductor/ShortRead#6]
Please consider adding:

```
URL: https://github.com/Bioconductor/ShortRead
BugReports: https://github.com/Bioconductor/ShortRead/issues
```

to the DESCRIPTION file, so this repo can be found from the package page <https://bioconductor.org/packages/release/bioc/html/ShortRead.html>.

**Comment by mtmorgan** [comment]
Happy to make these changes, but wondering (a) why URL to github.com instead of the package landing page (so that someone using the package can find out about it, including how to clone the source) or it's canonical source (https://git.bioconductor.org/packages/Bioconductor or even https://code.bioconductor.org/browse/ShortRead/) and (b) why point to GitHub issues rather than https://support.bioconductor.org/tag/ShortRead/ ?

**Comment by HenrikBengtsson** [comment]
> (a) why URL to github.com instead of the package landing page (so that someone using the package can find out about it

One can specify multiple, comma-separated URLs in the `URL` field, so it's not either or.  I use this myself on CRAN, e.g. https://cran.r-project.org/package=parallelly.

I personally think the "root" source location for a package should be listed as a URL.  This helps anyone who wish to look at the most-recent code base (which might not yet have been released on the repo, e.g. CRAN or Bioconductor) for troubleshooting and bug fixing.  It's also needed if you someone wants to do a PR.  Basically, it's nice to be able to identify the official home of the package without guessing.

You could add a URL to the Bioconductor landing page, which I guess should be the release page (<https://bioconductor.org/packages/release/bioc/html/ShortRead.html>).  I don't think I've seen anyone do that for CRAN packages, but I guess the assumption is that the page is on CRAN unless something else is specified.

> (b) why point to GitHub issues rather than https://support.bioconductor.org/tag/ShortRead/ ?

First, one can have only one URL under `BugReports` (otherwise you'll get an `R CMD check` NOTE).  This should be the URL where you want bug reports filed.  `utils::bug.report(package = "ShortReads")` will open that page.  If `BugReports` is not given, then `mailto:<maintainer-address>` is opened.

Personally, I find it odd to use a public forum for bug reports, but, I guess, if one gets lots of non-relevant issues, then one might want to direct people to another place first, to discuss the issue before claiming a bug.  OTH, you can configure the issue page here on GitHub with instructions to gate keep against poorly written bug reports, or feature requests, and you can even point people to <https://support.bioconductor.org/tag/ShortRead/> if they don't have a clear, reproducible bug report.  For an example of this, see <https://github.com/rstudio/rstudio/issues/new/choose>, which is configured in <https://github.com/rstudio/rstudio/tree/main/.github/ISSUE_TEMPLATE>.

**Comment by mtmorgan** [comment]
Thanks Henrik; for what it's worth `https://bioconductor.org/packages/ShortRead` is a shorter and more memorable path to the package landing page. It resolves to the current release branch or, if the package is 'in devel' only, the devel branch.
